title: 文章列表
description: My Personal learning notes
author: 王 英珍
github: https://github.com/wangyz666
about: 生信小鲜肉
disqus_shortname: learningnotes
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/snp.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-qq
      link: "http://user.qzone.qq.com/296085360/"
    - icon: fa-twitter
      link: "https://twitter.com/"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/wangyz666"

share:
  twitter_username: wangyz666
  fb_appid: ##

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
